import { Quicksand } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/common/Header";
import Footer from "@/common/Footer";
import Providers from "@/providers";

const inter = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TALKWED",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script
        async
        src="node_modules/@material-tailwind/html/scripts/ripple.js"
      ></script>

      <script
        async
        src="https://unpkg.com/@material-tailwind/html@latest/scripts/ripple.js"
      ></script>
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
