import { Quicksand } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/common/Header";
import Footer from "@/common/Footer";
import Providers from "@/providers";
import NextTopLoader from "nextjs-toploader";

const inter = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TALKWED",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="#5C148C" />

        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
