import Providers from "@/providers";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const inter = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TALKWED",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="#5C148C" />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
