export const config = {
  APP_ENV: `${process.env.NEXT_PUBLIC_APP_ENV}`,
  APP_URL: `${process.env.NEXT_PUBLIC_APP_URL}`,
  API_URL: `${process.env.NEXT_PUBLIC_REST_API_ENDPOINT}`,
  MAPS_API: `${process.env.NEXT_PUBLIC_GOOGLE_API_KEY}`,
  HUBSPORT_ACCESS_TOKEN: `${process.env.NEXT_PUBLIC_HUBSPORT_ACCESS_TOKEN}`,
  HUBSPORT_PORTAL_ID: `${process.env.NEXT_PUBLIC_HUBSPORT_PORTAL_ID}`,
  HUBSPORT_REVIEW_FORM_ID: `${process.env.NEXT_PUBLIC_HUBSPORT_REVIEW_FORM_ID}`,
  HUBSPORT_COMPLAINT_FORM_ID: `${process.env.NEXT_PUBLIC_HUBSPORT_COMPLAINT_FORM_ID}`,
  IFRAME_URL: `${process.env.NEXT_PUBLIC_IFRAME_URL}`,
  REVIEWS_IFRAME_URL: `${process.env.NEXT_PUBLIC_REVIEWS_IFRAME_URL}`,
  GOOGLE_ANALYTICS_ID: `${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`,
};
